[project]
name = "invoice-generator"
version = "0.1.0"
description = "invoice generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "myutils",
    "pdfme>=0.5.0",
]

[tool.uv.sources]
myutils = { workspace = true }
