[project]
name = "tools"
version = "0.1.0"
description = "misc tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "myutils",
    "pdfplumber>=0.11.9",
    "pypdf2>=3.0.1",
]

[tool.uv.sources]
myutils = { workspace = true }
